# Generated by Django 4.1.7 on 2023-02-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
