# Generated by Django 4.1.7 on 2023-02-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_appointment_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doc',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
